name: Essential Checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.18"
      - name: install npm dependencies
        run: npm install
        working-directory: ./
      - name: Running Jest Tests
        run: npm run test
        working-directory: ./
